/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package javafx.gradle.template;

import javafx.application.Application;
import javafx.geometry.Pos;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.StackPane;
import javafx.stage.Stage;

public class App extends Application {

    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        launch();
    }

    @Override
    public void start(Stage stage) {
        int width = 500;
        int height = 500;

        Label hello = new Label("Hello world!");
        StackPane pane = new StackPane(hello);
        pane.setAlignment(Pos.CENTER);

        Scene scene = new Scene(pane, width, height);
        stage.setScene(scene);
        stage.show();
    }
}
